Lab_2_JoseDiaz/Controllers/AVLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.ArbolValanceadoUtils;
using Lab_2_JoseDiaz.Entities;

namespace Lab_2_JoseDiaz.Controllers
{
    public class AVLController : Controller
    {
        public static int total;
        readonly IAVLRepository aVLRepository;
        public static List<CarritoEntity> carritoDeCompras = new List<CarritoEntity>();
        public static List<FarmacoEntity> s = new List<FarmacoEntity>();
        public static List<FarmacoEntity> SinInventario = new List<FarmacoEntity>();
        public static ClienteViewModel persona = new ClienteViewModel();

        public AVLController(IAVLRepository aVLRepository)
        {
            this.aVLRepository = aVLRepository;
            aVLRepository.LoadFile();
        }

        // GET: AVL
        public ActionResult Index(string SearchString, int page = 1)
        {
            ViewBag.PageNum = page;
            List<FarmacoEntity> listafarmacos = new List<FarmacoEntity>();

            if (string.IsNullOrEmpty(SearchString))
            {
                listafarmacos.Clear();

                return View(listafarmacos);
            }
            else
            {
                listafarmacos.Clear();
                ViewBag.SearchString = SearchString;

                listafarmacos = aVLRepository.BuscarFarmacos(SearchString, page, 5);
                ViewBag.ele = aVLRepository.Buscar(SearchString).Count;
                ViewBag.total = ((aVLRepository.Buscar(SearchString).Count) / 5) + 1;
                s = listafarmacos;
                return View(listafarmacos.FindAll(x => x.Existencia > 0));

            }
        }

        // GET: AVL/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AVL/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AVL/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AVL/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AVL/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AVL/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AVL/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Controllers/ArbolBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.ArbolBUtils;
using Lab_2_JoseDiaz.Entities;
using Lab_2_JoseDiaz.ArbolBinarioUtils;

namespace Lab_2_JoseDiaz.Controllers
{
    public class ArbolBController : Controller
    {

        public static int total;
        readonly IArbolBRepository arbolBRepository;
        public static List<CarritoEntity> carritoDeCompras = new List<CarritoEntity>();
        public static List<FarmacoEntity> s = new List<FarmacoEntity>();
        public static List<FarmacoEntity> SinInventario = new List<FarmacoEntity>();
        public static ClienteViewModel persona = new ClienteViewModel();

        public ArbolBController(IArbolBRepository arbolBRepository)
        {
            this.arbolBRepository = arbolBRepository;
            arbolBRepository.LoadFile();
        }

        // GET: ArbolB
        public ActionResult Index(string SearchString, int page = 1)
        {

            ViewBag.PageNum = page;
            List<FarmacoEntity> listafarmacos = new List<FarmacoEntity>();

            if (string.IsNullOrEmpty(SearchString))
            {
                listafarmacos.Clear();

                return View(listafarmacos);
            }
            else
            {
                listafarmacos.Clear();
                ViewBag.SearchString = SearchString;

                listafarmacos = arbolBRepository.BuscarFarmacos(SearchString, page, 5);
                ViewBag.ele = arbolBRepository.Buscar(SearchString).Count;
                ViewBag.total = ((arbolBRepository.Buscar(SearchString).Count) / 5) + 1;
                s = listafarmacos;
                return View(listafarmacos.FindAll(x => x.Existencia > 0));

            }


        }

        public ActionResult Productos()
        {
            string total;
            total = arbolBRepository.Total_compra(carritoDeCompras);
            ViewBag.precioFinal = total;
            persona.total = total;
            return View(carritoDeCompras);
        }

        // GET: ArbolBinario/Details/5
        public ActionResult Details(string id, int SearchInt)
        {
            FarmacoEntity farmaco = s.Find(x => x.Nombre == id);
            if (SearchInt == 0 || string.IsNullOrEmpty(Convert.ToString(SearchInt)))
            {

                return View(farmaco);
            }
            else
            {
                CarritoEntity carrito = new CarritoEntity();
                ViewBag.SearchInt = SearchInt;

                //Metodo para editar los valores del arbol y del archivo de texto va aquí
                farmaco.Existencia -= SearchInt;
                arbolBRepository.Modificar(id, farmaco.Existencia);

                carrito.Nombre = farmaco.Nombre;
                carrito.Precio = farmaco.Precio;
                carrito.Descripcion = farmaco.Descripcion;
                carrito.CasaProductora = farmaco.CasaProductora;
                carrito.cantidad = SearchInt;
                carrito.total = carrito.Precio * carrito.cantidad;
                carritoDeCompras.Add(carrito);
                TempData["msg"] = "<script>alert('Añadido al carrito');</script>";
                return View(farmaco);
            }


        }

        // GET: ArbolBinario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArbolBinario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm]ClienteViewModel cliente)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    Facturacion f = new Facturacion();
                    // TODO: Add insert logic here
                    persona.nombre = cliente.nombre;
                    persona.nit = cliente.nit;
                    persona.direccion = cliente.nit;
                    cliente.total = persona.total;
                    f.CrearFactura(cliente, carritoDeCompras);
                    TempData["a"] = "<script>alert('Compra realizada con éxito');</script>";
                    carritoDeCompras.Clear();
                    cliente.total = "0";

                    return Redirect("Productos");

                }
                else
                {
                    return Redirect("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: ArbolBinario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ArbolBinario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ArbolBinario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ArbolBinario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Controllers;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.Entities;

namespace Lab_2_JoseDiaz.Controllers
{
    public class EmpleadoController : Controller
    {
        readonly IEmpleadoRepository empleadoRepository;
        public EmpleadoController(IEmpleadoRepository empleadoRepository)
        {
            this.empleadoRepository = empleadoRepository;
        }

        // GET: Empleado con todo y busqueda implementada 
        public ActionResult Index(string SearchString, string identi, string horas)
        {

                if (string.IsNullOrEmpty(SearchString) && string.IsNullOrEmpty(identi) && string.IsNullOrEmpty(horas)) 
                {

                    List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados();
                    return View(listaEmpleados);
                }
                else
                {
                    List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados().FindAll(x => x.Nombre.Contains(SearchString) || x.Id == Convert.ToInt32(identi) || x.horas_trabajadas == Convert.ToDouble(horas));

                    ViewBag.SearchString = SearchString;
                    ViewBag.SearchHoras = horas;
                    ViewBag.SearchID = identi;
                    return View(listaEmpleados);

                }
                          

        }
        
        public ActionResult Oficina()
        {
            List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados().FindAll(x => x.Estado == true);
            return View(listaEmpleados);
        }
        public ActionResult OfiF()
        {
            List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados().FindAll(x => x.Estado == false);
            var count = listaEmpleados.Count(x => x != null);
            return View(listaEmpleados);
        }


        // GET: Empleado/Details/5
        public ActionResult Details(int id)
        {
            EmpleadoViewModel empleado = empleadoRepository.ObtenerEmpleado(id);
            return View(empleado);
        }
        //Todo esto crea un nuevo empleado
        // GET: Empleado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Empleado/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm]EmpleadoViewModel empleado)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    // TODO: Add insert logic here
                    
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(empleado);
                }

            }
            catch
            {
                return View();
            }
        }
                      

        // GET: Empleado/Edit/5
        public ActionResult Edit(int id)
        {
            EmpleadoViewModel empleado = empleadoRepository.ObtenerEmpleado(id);
            return View(empleado);
        }

        // POST: Empleado/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [FromForm]EmpleadoViewModel empleado)
        {
            try
            {
                empleadoRepository.ModificarEmpleado(empleado);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Empleado/Delete/5
        public ActionResult Delete(int id)
        {
            EmpleadoViewModel empleado = empleadoRepository.ObtenerEmpleado(id);
            return View(empleado);
        }

        // POST: Empleado/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [FromForm] EmpleadoViewModel empleado)
        {
            try
            {
                // TODO: Add delete logic here
                empleadoRepository.QuitarEmpleado(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Controllers/SimulacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Controllers;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.Entities;
namespace Lab_2_JoseDiaz.Controllers
{
    public class SimulacionController : Controller
    {
        readonly IEmpleadoRepository empleadoRepository;
        public SimulacionController(IEmpleadoRepository empleadoRepository)
        {
            this.empleadoRepository = empleadoRepository;
        }

        // GET: Simulacion
        public ActionResult Index()
        {
            List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados();
            empleadoRepository.SimularSalidas();
            return View(listaEmpleados);
        }

        public ActionResult Terminar()
        {
            List<EmpleadoViewModel> listaEmpleados = empleadoRepository.ObtenerEmpleados();
                       
            empleadoRepository.CalcularSalario();
            return View(listaEmpleados);
        }

        // GET: Simulacion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Simulacion/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Simulacion/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Simulacion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Simulacion/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Simulacion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Simulacion/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_2_JoseDiaz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*Boton principal*@
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Farmacos SA</a>
                @*Aqui se agregan los botones*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Acerca de nosotros</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                    <li><a asp-area="" asp-controller="Empleado" asp-action="Index">Empleados</a></li>
                    <li><a asp-area="" asp-controller="Simulacion" asp-action="Index">Simulación 1</a></li>
                    <li><a asp-area="" asp-controller="Simulacion" asp-action="Terminar">Terminar el dia</a></li>
                    <li><a asp-area="" asp-controller="ArbolBinario" asp-action="Index">Fármacos</a></li>
                    <li><a asp-area="" asp-controller="AVL" asp-action="Index">AVL</a></li>
                    <li><a asp-area="" asp-controller="ArbolB" asp-action="Index">Arbol B</a></li>
                    <li><a asp-area="" asp-controller="ArbolBinario" asp-action="Rellenar">llenar stock</a></li>
                    <li><a asp-area="" asp-controller="ArbolBinario" asp-action="Productos">Carrito</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - José Díaz</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>