Lab_2_JoseDiaz/Controllers/AVLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.ArbolValanceadoUtils;
using Lab_2_JoseDiaz.Entities;

namespace Lab_2_JoseDiaz.Controllers
{
    public class AVLController : Controller
    {
        public static int total;
        readonly IAVLRepository aVLRepository;
        public static List<CarritoEntity> carritoDeCompras = new List<CarritoEntity>();
        public static List<FarmacoEntity> s = new List<FarmacoEntity>();
        public static List<FarmacoEntity> SinInventario = new List<FarmacoEntity>();
        public static ClienteViewModel persona = new ClienteViewModel();

        public AVLController(IAVLRepository aVLRepository)
        {
            this.aVLRepository = aVLRepository;
            aVLRepository.LoadFile();
        }

        // GET: AVL
        public ActionResult Index(string SearchString, int page = 1)
        {
            ViewBag.PageNum = page;
            List<FarmacoEntity> listafarmacos = new List<FarmacoEntity>();

            if (string.IsNullOrEmpty(SearchString))
            {
                listafarmacos.Clear();

                return View(listafarmacos);
            }
            else
            {
                listafarmacos.Clear();
                ViewBag.SearchString = SearchString;

                listafarmacos = aVLRepository.BuscarFarmacos(SearchString, page, 5);
                ViewBag.ele = aVLRepository.Buscar(SearchString).Count;
                ViewBag.total = ((aVLRepository.Buscar(SearchString).Count) / 5) + 1;
                s = listafarmacos;
                return View(listafarmacos.FindAll(x => x.Existencia > 0));

            }
        }

        // GET: AVL/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AVL/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AVL/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AVL/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AVL/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AVL/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AVL/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Controllers/ArbolBinarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab_2_JoseDiaz.Models;
using Lab_2_JoseDiaz.Repository;
using Lab_2_JoseDiaz.ArbolBinarioUtils;
using Lab_2_JoseDiaz.Entities;

namespace Lab_2_JoseDiaz.Controllers
{
    public class ArbolBinarioController : Controller
    {
        public static int total;
        readonly IArbolBinarioRepository arbolBinarioRepository;
        public static List<CarritoEntity> carritoDeCompras = new List<CarritoEntity>();
        public static List<FarmacoEntity> s = new List<FarmacoEntity>();
        public static List<FarmacoEntity> SinInventario = new List<FarmacoEntity>();
        public static ClienteViewModel persona = new ClienteViewModel();
        
        public ArbolBinarioController(IArbolBinarioRepository arbolBinarioRepository)
        {
            this.arbolBinarioRepository = arbolBinarioRepository;
            arbolBinarioRepository.LoadFile();
        }        
        // GET: ArbolBinario Creación de la tabla principal
        public ActionResult Index(string SearchString, int page = 1)
        {
            
            ViewBag.PageNum = page;
            List<FarmacoEntity> listafarmacos = new List<FarmacoEntity>();          
            
            if (string.IsNullOrEmpty(SearchString))
            {
                listafarmacos.Clear();
                
                return View(listafarmacos);
            }
            else
            {
                listafarmacos.Clear();
                ViewBag.SearchString = SearchString;
                
                listafarmacos = arbolBinarioRepository.BuscarFarmacos(SearchString, page, 5);
                ViewBag.ele = arbolBinarioRepository.Buscar(SearchString).Count;
                ViewBag.total = ((arbolBinarioRepository.Buscar(SearchString).Count)/5)+1;
                s = listafarmacos;
                return View(listafarmacos.FindAll(x => x.Existencia > 0));               
                
            }
            
            
        }
        public ActionResult Rellenar()
        {
            List<FarmacoEntity> rellenar = new List<FarmacoEntity>();
            rellenar = arbolBinarioRepository.Recorrer(0);
            return View(rellenar);
        }

        public ActionResult Actualizar()
        {
            List<FarmacoEntity> rellenar = new List<FarmacoEntity>();
            rellenar = arbolBinarioRepository.Recorrer(0);
            arbolBinarioRepository.Simulacion(rellenar);
            return Redirect("Index");
        }

        public ActionResult Productos()
        {            
            string total;
            total = arbolBinarioRepository.Total_compra(carritoDeCompras);
            ViewBag.precioFinal = total;
            persona.total = total;
            return View(carritoDeCompras);
        }

        // GET: ArbolBinario/Details/5
        public ActionResult Details(string id, int SearchInt)
        {
            FarmacoEntity farmaco = s.Find(x => x.Nombre == id);
            if (SearchInt == 0 || string.IsNullOrEmpty(Convert.ToString(SearchInt)))
            {
                
                return View(farmaco);
            }
            else
            {
                CarritoEntity carrito = new CarritoEntity();                
                ViewBag.SearchInt = SearchInt;

                //Metodo para editar los valores del arbol y del archivo de texto va aquí
                farmaco.Existencia -= SearchInt;
                arbolBinarioRepository.Modificar(id, farmaco.Existencia);

                carrito.Nombre = farmaco.Nombre;
                carrito.Precio = farmaco.Precio;
                carrito.Descripcion = farmaco.Descripcion;
                carrito.CasaProductora = farmaco.CasaProductora;
                carrito.cantidad = SearchInt;
                carrito.total = carrito.Precio * carrito.cantidad;
                carritoDeCompras.Add(carrito);
                TempData["msg"] = "<script>alert('Añadido al carrito');</script>";
                return View(farmaco);
            }
            
            
        }     
        
        // GET: ArbolBinario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArbolBinario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm]ClienteViewModel cliente)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    Facturacion f = new Facturacion();
                    // TODO: Add insert logic here
                    persona.nombre = cliente.nombre;
                    persona.nit = cliente.nit;
                    persona.direccion = cliente.nit;
                    cliente.total = persona.total;
                    f.CrearFactura(cliente, carritoDeCompras);
                    TempData["a"] = "<script>alert('Compra realizada con éxito');</script>";
                    carritoDeCompras.Clear();                    
                    cliente.total = "0";
                    
                    return Redirect("Productos");

                }
                else
                {
                    return Redirect("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: ArbolBinario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ArbolBinario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ArbolBinario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ArbolBinario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab_2_JoseDiaz/Views/AVL/Create.cshtml
@model Lab_2_JoseDiaz.Models.ClienteViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ClienteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="direccion" class="control-label"></label>
                <input asp-for="direccion" class="form-control" />
                <span asp-validation-for="direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nit" class="control-label"></label>
                <input asp-for="nit" class="form-control" />
                <span asp-validation-for="nit" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
                
            </div>
        </form>
    </div>
</div>

<div>

    <a asp-action="Index">Back to List</a>
    @Html.Raw(TempData["a"])
</div>

Lab_2_JoseDiaz/Views/AVL/Details.cshtml
@model Lab_2_JoseDiaz.Entities.FarmacoEntity

@{
    ViewData["Title"] = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            Casa productora
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CasaProductora)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Precio) ($)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Existencia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Existencia)
        </dd>
    </dl>
</div>
<form asp-controller="ArbolBinario" asp-action="Details" method="get">
    <input type="number" name="SearchInt" @*@*value="@ViewBag.SearchInt"*@*@ value="0" min="0" max="@Model.Existencia" />
    <input type="submit" value="Añadir al carrito" />
    @Html.Raw(TempData["msg"])
</form>

<div>
    
    <a asp-controller="ArbolBinario" asp-action="Index">Seguir comprando</a>
</div>

Lab_2_JoseDiaz/Views/AVL/Index.cshtml
@model IEnumerable<Lab_2_JoseDiaz.Entities.FarmacoEntity>

@{
    ViewData["Title"] = "Index";
}


<h2>Index</h2>

<p>
    <form asp-controller="ArbolBinario" asp-action="Index" method="get">
<p>
    Nombre del producto: <input type="text" name="SearchString" value="@ViewBag.SearchString" />
    <input type="submit" value="Search" />
    Total de resultados: @ViewBag.ele
</p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Descripción
            </th>
            <th>
                Casa productora
            </th>
            <th>
                Precio ($)
            </th>
            <th>
                Existencia
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CasaProductora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Existencia)
                </td>
                <td>
                    @Html.ActionLink("Comprar", "Details", new { id = item.Nombre })

                </td>

            </tr>
        }
    </tbody>
</table>

<div class="container">
    <div class="col-xs-4 col-sm-offset-4">
        @if (ViewBag.PageNum > 1)
        {
            <a class="btn btn-default" href="@Url.Action("Index", new {SearchString = ViewBag.SearchString, page = ViewBag.PageNum - 1 })">Anterior</a>
        }
        @if (ViewBag.PageNum < ViewBag.total)
        {
            <a class="btn btn-default" href="@Url.Action("Index", new {SearchString = ViewBag.SearchString, page = ViewBag.PageNum + 1 })">Siguiente</a>
        }

    </div>
    Total de páginas: @ViewBag.total
</div>

Lab_2_JoseDiaz/Views/AVL/Productos.cshtml
@model IEnumerable<Lab_2_JoseDiaz.Entities.CarritoEntity>

@{
    ViewData["Title"] = "Productos";
}

<h2>Productos</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                Casa productora
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cantidad)
            </th>
            <th>
                Subtotal ($)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CasaProductora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            
        </tr>
}
        
    </tbody>
</table>
<p>
    <b> Total a pagar</b> $.@ViewBag.precioFinal
</p>
<form asp-controller="ArbolBinario" asp-action="Create" method="get">
    <input type="submit" value="Comprar" />
</form>

Lab_2_JoseDiaz/Views/AVL/Rellenar.cshtml
@model IEnumerable<Lab_2_JoseDiaz.Entities.FarmacoEntity>

@{
    ViewData["Title"] = "Rellenar";
}

<h2>Rellenar</h2>

<p>
    <a asp-action="Actualizar">Rellenar productos</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                Casa productora
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio) ($)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Existencia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CasaProductora)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Existencia)
            </td>
            
        </tr>
}
    </tbody>
</table>